<?php
$title = 'Posts';
$this->headTitle($title);
?>
<script>
   $(document).ready(function() {
       $('#postTable').DataTable({
               "ajax": '/postlist'
           });

       });

</script>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p><a href="<?php echo $this->url('addpost'); ?>">Add new Post</a></p>
<table id="postTable" class="display" width="100%" cellspacing="0">
        <thead>
            <tr>
                <th>Post Title</th>
                <th>Category</th>
                <th>Summary</th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tfoot>
            <tr>
                <th>Post Title</th>
                <th>Category</th>
                <th>Summary</th>
                <th></th>
                <th></th>
            </tr>
        </tfoot>
    </table>