<?php
$title = 'Add Category';
$this->headTitle($title);
?>
<h3><?php echo $this->escapeHtml($title); ?></h3>

<form class="" id="categoryForm" method="post" action="/addcategory" enctype="multipart/form-data">
    <div class="form-group has-danger">
        <div class="form-control-feedback" style="color: red"><?= isset($this->errMsg) ? $this->errMsg : '' ?></div>
    </div>
    <div class="form-group" style="width: 300px;">
        <label for="categoryName">Category Name</label>
        <input class="form-control" id="categoryName" name="categoryName" type="text" required>
    </div>
    <div class="form-group" style="width: 300px;">
        <label for="description">Description</label>
        <textarea class="form-control" id="description" name="description"></textarea>
    </div>
    <div class="form-group" style="width: 300px;">
        <input class="submit btn btn-primary" type="submit" value="Submit" id="categorySubmit" required>
    </div>
</form>